services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
