services:
  - type: web
    name: portfolio-website
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    rootDir: .
    envVars:
      - key: PORT
        value: 5000
